### ISSUE TITLE
simple here sentinel

### ISSUE THREAD

**Issue by jennybc** [krlmlr/here#1]
You will notice my recent [ode to here](https://github.com/jennybc/here_here#readme).

When explaining how `here::here()` "just works", I wished that were even more true, even if someone doesn't use RStudio. My rationale is 50% functionality, 50% optics. This is also why I proposed elevating Git-repository-hood over in rprojroot (https://github.com/krlmlr/rprojroot/issues/20). I think it would be a valid heuristic for here, because many people use Git (and/or it's a practice that is easy to recommend!).

What do you think of adding a criterion to `here()` that just looks for a file named `.here`, using `has_file()` under the hood? Plus a simple initializer that just does `touch .here`. Then it's really easy to make `here::here()` "just work" for literally anyone, regardless of their IDE.

**Comment by jennybc** [comment]
This is both inspirational and possibly relevant for ESS people:

http://batsov.com/projectile/

I don't know if many ESS users use projectile? Maybe @lionel- knows.

**Comment by lionel-** [comment]
I have no idea. I know that @vspinu uses it though :)

**Comment by krlmlr** [comment]
I like the idea of a sentinel specific to "here"; using .git is also fine for me. It could be advertised in the error/startup message (including the reason why `here` thinks this is the project root if one is found).

Projectile seems to have its own root discovery, I have no idea how to couple this with rprojroot.

**Comment by lionel-** [comment]
projectile recognises `.projectile` files and version control repositories.

**Comment by vspinu** [comment]
Projectile recognizes a [long list](https://github.com/vspinu/projectile/blob/master/projectile.el#L288-L344) of root files but I am not sure I understand how that relates to this project.

 @krlmlr what is the use case that made you create the project? Is this for end user to manage scripts or for package developers?

**Comment by krlmlr** [comment]
It's primarily for the end user.

**Comment by jennybc** [comment]
I don't think projectile does relate to this. I was wondering if, in the years since I left ESS, a notion of project had emerged, signified by something like `foo.Rproj`. I have absorbed from this discussion that the answer is NO.

**Comment by lionel-** [comment]
@jennybc what do you think is missing? Just to know what I'm missing out :)

**Comment by jennybc** [comment]
@lionel- This is not directly related to here, but indirectly I guess it actually is.

I like to have many R projects (conceptual def'n) open at once. Some are packages, some are websites, some are data analyses, etc. With my RStudio workflow, I use Projects for all (Rstudio def'n) and have one instance open per Project:

![much-rstudio](https://cloud.githubusercontent.com/assets/599454/21437261/b3bb3a96-c837-11e6-94c0-e1841223afd8.jpg)

Each instance has its own companion R process with working directory set to top-level directory, file browser pointed at same, etc. I move my attention between them all day.

I never got to this level of workflow nirvana with Emacs + ESS. Therefore it was much more cumbersome to context switch. Sure, opening `.R` files from multiple projects was easy, but I generally kept only 1 R process running. Then, because I communicated with a common R process from distinct project, I had some silly-but-standardized workarounds in scripts re: working directory and paths.

It's entirely possible that my Emacs/ESS usage was inexpert.
