### ISSUE TITLE
Override current `here`

### ISSUE THREAD

**Issue by kpjonsson** [krlmlr/here#13]
Is there anyway to override the directory `here()` picks? To me it seems like you can't, so if it's not your preferred directory you just have to restart your R session.

**Comment by krlmlr** [comment]
Yes, *here* determines the project root only once, when the package is loaded. The features the *here* package offers are very limited, by design. Take a look at the much more powerful *rprojroot* package for many more options.

**Comment by kpjonsson** [comment]
@krlmlr All right, thanks for the reply.
