### ISSUE TITLE
Error with here+knitr

### ISSUE THREAD

**Issue by chris-prener** [krlmlr/here#14]
Hey @krlmlr - I am not 100% sure this is a problem with `here`, but I thought I would start "here" and see what you thought. I apologize for this being long winded...

I have students use `here` at the top of R notebooks that they write individual assignments up in. Their notebooks are embedded in a folder structure that looks like this:

```
assignment/
   assignment.Rproj
   
   data/
      data.csv

   docs/
      assignment.Rmd
      assignment.nb.html
```

There is a common syntax they use at the top of each notebook to make sure that the root directory for their notebook is set to the directory with the `.Rproj` file, which looks like this:

```
knitr::opts_knit$set(root.dir = here::here())
```

You can see an example of how this works in this [assignment replication](https://github.com/slu-soc5650/lecture-03/tree/master/Lab-02/lab-02-replication). You'll notice that the example is similarly laid out, with a `csv` file in the `data` subdirectory and a notebook in the `docs` subdirectory.

In that specific assignment, I had a number of students get errors when they went to load data from the `data` subdirectory:

```
> riverData <- read_csv("data/MO_HYDRO_ImpairedRiversStreams.csv")
Error: 'MO_HYDRO_ImpairedRiversStreams.csv' does not exist in current working directory ('C:/Users/Owner/Documents/GitHub/DoeAssignments/Labs/Lab-02/docs')
```

or 

```
damsRaw <- read.csv("data/MO_HYDRO_Dams.csv")
#> Warning in file(file, "rt"): cannot open file 'data/MO_HYDRO_Dams.csv': No
#> such file or directory
#> Error in file(file, "rt"): cannot open the connection
```

As you can see, the errors happen with both `readr` as well as the base `R` `read.csv()` function, so I am reasonably sure that the issue is not specific to the function that is being used to import data but rather something else. I also manually verified with both students that the folders existed where they should have and that there were no spelling errors in their code.

In both students' cases, they were using the "Run All Chunks Above" button to execute a number of chunks including that first setup chunk. I verified that this executed the setup code chunk with the root directory function shown above (you could see a record of it being run in the console). However, the notebook did not switch its root directory, and thus was trying to find the `data/MO_HYDRO_ImpairedRiversStreams.csv` within the `docs` subdirectory.

However, when we executed each chunk manually with the "Run Current Chunk" button, the root directory was reset and they were able to load the data without error. 

The only commonality between the two students, other than the same folder structure and data source, is that they were both on Windows laptops.

My sense is that either `here` is not actually feeding the notebook the right file path when the code chunk gets executed as part of the "Run All Chunks Above" process *or* that the `opts_knit$set(root.dir = here())` process is not actually setting what it gets from `here`. I'm not sure which of these is the answer, however.

Any thoughts you have on whether this is a bug with `here` or what else might be causing it would be very much appreciated! We have a workaround for now (executing code manually the first time) but it would be great to address this in a more sustainable way.

**Comment by krlmlr** [comment]
A different way to handle it would be to avoid changing the `root.dir` setting and just always use *here* to address files, e.g. `here("data", "data.csv")`. I don't know how well *here* works if used for `root.dir`.

**Comment by chris-prener** [comment]
thanks for the quick response @krlmlr - so it would look something like this - `df <- read_csv(here("data", "data.csv"))`?

**Comment by krlmlr** [comment]
Yes, this pattern must be used consistently. It might help to define shortcuts (functions or variables).

**Comment by chris-prener** [comment]
OK I'll keep this in my back pocket if/when these errors crop up again - thanks so much!

**Comment by dwhdai** [comment]
@krlmlr @chris-prener I'm experiencing this issue when compiling an RMarkdown document that sources an R script in another subdirectory. 


    root/
    .Rproj
        reports/
            report.Rmd

        scripts/
            script_subfolder/
                script.R

When executing from the notebook into console, `source(here("scripts", "script_subfolder", "script.R"))` works, but not when compiling the .Rmd into HTML. Any reason why this might be the case and have a work-around?

**Comment by dwhdai** [comment]
> @krlmlr @chris-prener I'm experiencing this issue when compiling an RMarkdown document that sources an R script in another subdirectory.
> 
> ```
> root/
> .Rproj
>     reports/
>         report.Rmd
> 
>     scripts/
>         script_subfolder/
>             script.R
> ```
> When executing from the notebook into console, `source(here("scripts", "script_subfolder", "script.R"))` works, but not when compiling the .Rmd into HTML. Any reason why this might be the case and have a work-around?

Just found my issue. My `here()` was masked by another function from another package. Specifying the package using `here::here()` fixed this.

**Comment by krlmlr** [comment]
Thanks. The _conflicted_ package solves this particular problem.
