### ISSUE TITLE
Allow for RegEx in here?

### ISSUE THREAD

**Issue by cportner** [krlmlr/here#15]
First, thank you for an excellent package.

Second, is there a way to allow for RegEx inside here? I am looking to delete some files automatically once I have processed them, but the file extension case varies. Some are ".zip", and others are ".Zip", etc. I could write one unlink for each case combination, but allowing something like
```
unlink(here("data", "*.(?i)zip))"
```
would be great. The "*" part works, but the (?i) part does not.

**Comment by krlmlr** [comment]
This doesn't seem to be relevant to *here*, because `here()` only connects path components. The logic happens in `unlink()`, wildcards are supported but regexes are not.
