### ISSUE TITLE
A here class?

### ISSUE THREAD

**Issue by boshek** [krlmlr/here#16]
Such a great package. Thank you for developing it. 

I am wondering if there are any plans to implement a `here` class so that we can efficiently get deeper into a directory using a previously defined `here` object. For example:

```
> library(here)
> data_dir <- here("data")
> data_dir
[1] "C:/_dev/data"
> data1 <- here(data_dir,"data1","data1.csv")
> data1
[1] "C:/_dev/C:/_dev/data/data1/data1.csv"
```
I tripped myself up recent when I tried to re-use a path created by `here` in this manner. 

If not can you recommend an alternative approach when you are building paths that go deeper into a directory?

**Comment by krlmlr** [comment]
Thanks. I intend to keep this package very simple on purpose. The functionality is available in the *rprojroot* package via e.g.

```r
rprojroot::is_r_package$make_fix_file(subdir = "tests")
```

thanks to @BarkleyBG.

**Comment by boshek** [comment]
Thanks. This seems reasonable.
