### ISSUE TITLE
Add a strict option?

### ISSUE THREAD

**Issue by karldw** [krlmlr/here#5]
I find myself doing things like this:
```r
PROJ_ROOT <- here::here()
stopifnot(normalizePath(PROJ_ROOT) != normalizePath(getwd()))
```
Do you think it would make sense to add an option making `here` more strict?  Or should I just be using `rprojroot::find_root` if I want that level of control?

**Comment by krlmlr** [comment]
Thanks. What is your use case, why is it important to have the working directory in the project root?

**Comment by karldw** [comment]
Ah, sorry, I realize that wasn't clear. When `here` can't find any matching criteria, it just returns the working directory. I don't expect to have the working directory as the project root, so I'm running `here()` then testing if it gave me the working directory back.

 I was thinking a `strict` option would allow `here` to be a little more severe, raising an error when no matching criteria are found.

**Comment by krlmlr** [comment]
Interesting. I don't like the idea of a new argument to `here()`, but I'm open to alternative suggestions. For now I'd say the safest bet is to use rprojroot.

**Comment by karldw** [comment]
Sounds good, thanks!
