### ISSUE TITLE
Provide ability to temporarily override "here" directory

### ISSUE THREAD

**Issue by hadley** [krlmlr/here#6]
I'm considering ditching the `base_path` parameter in all the usepackage functions and instead using `here::here()`.  It would be nice if there was some easy way to temporary set the "here" directory somewhere else for testing.

**Comment by krlmlr** [comment]
If `here()` is used as default value for a (still existing) `base_path` argument, we could manually override in tests. If it's purely internal, why not wrapping with

```r
my_here <- function(...) here::here(...)
```

and using `mockr::with_mock(my_here = ..., ...)` for tests?

**Comment by hadley** [comment]
This would be a systematic change to the API of usethis - instead of supplying the `base_path` it would become a global variable. This simplifies the API (since 99% of people will never touch `base_path`) and eliminates a frequent source of bugs (I've forgotten to pass `base_path` down). But then I need someway to override the "current" project/package, and it would be nice to simply depend on here for that, rather than adding another wrapper.

**Comment by hadley** [comment]
Ok, I'll just implement this in usethis

**Comment by krlmlr** [comment]
Can you please ping me at/point me to the relevant usethis commit?

**Comment by hadley** [comment]
See https://github.com/r-lib/usethis/blob/master/R/proj.R

**Comment by krlmlr** [comment]
Thanks, this looks like a robust solution to me. If it helps, I can export `here:::is_here` that you could use instead of `proj_crit()`. (It's currently a variable, maybe make it a function for exporting.)

I'd rather keep "here" as simple as possible.
