### ISSUE TITLE
How to play more nicely with file path expansion?

### ISSUE THREAD

**Issue by jennybc** [krlmlr/here#7]
In a recent twitter-storm about project-based thinking and file paths, a really good point was raised that I too have felt (sorry, I can't find the tweet now).

RStudio, for example, does tab completion on filenames within a Project, which is very handy.

But then `here::here()` expects the path parts separated out into a character vector.

Is there a way to have our cake and eat it too? Could the relative paths produced by RStudio be acceptable to `here::here()`? Or could there be a helper function or add-in that converts these easy-to-get paths into the proper form?

**Comment by krlmlr** [comment]
I think you can still use the path as one single string in `here()`, like in `here("tests/testthat")`. I just checked, this is what RStudio generates when I auto-complete `testthat`. We have no code that checks for slashes. Maybe we can add an example that clarifies this?

**Comment by jennybc** [comment]
Would such paths retain portability to, say, Windows? I guess I’ve always assumed that separate parts was a best practice, but maybe it is unnecessary.

**Comment by krlmlr** [comment]
Windows accept slashes, mostly. In my experience, problems arise if they get converted to backslashes and you try to compare paths and find they're different even if they are the same. So, code that works on Linux/OS X may fail on Windows.

I just checked, `here::here("a", "b")` returns a path with slashes also on Windows. We could look for backslashes in the path and warn users, but that would be the responsibility of rprojroot.
