### ISSUE TITLE
Avoid stripping trailing / to specify a directory

### ISSUE THREAD

**Issue by lgaborini** [krlmlr/here#9]
Hello,
I am using `here` to automate `knitr` report creation by moving report and data files in separate directories, `/reports` and `/data`. The common root is the `here` directory.

However, I would like to specify a prefix to save `knitr` figures in subdirectory `/reports/fig`.   
`knitr` requires a trailing slash to specify directories.   
Using `here('reports', 'fig/')` strips the trailing `/`, thus e.g., figure `img_01.png` is outputted as `/reports/figimg_01.png` instead of `/reports/fig/img_01.png`.

Currently I have to manually paste: `paste0(here('reports', 'fig'), '/')`, but this becomes cumbersome.

Thank you!

**Comment by krlmlr** [comment]
The following works for me:

``` r
here::here("reports", "fig", "")
#> [1] "/tmp/RtmpMnOm7X/reports/fig/"
```

> Created on 2018-02-01 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

I'll add a test to make sure that this stays that way.

**Comment by krlmlr** [comment]
...doesn't work on Windows, but works on Linux. This is because `here()` is using `file.path()` under the hood, and this will strip trailing slashes as documented.

This feels like a sufficiently rare use case to me, and I'd rather stick with the current behavior. Thanks anyway for raising this.

**Comment by krlmlr** [comment]
Closing in favor of https://github.com/r-lib/fs/issues/96.
